#!/bin/python
import requests
import sys
import time

trackingCode=str(sys.argv[1])

# Este script utiliza um usuário de teste 
user = 'teste'
token = '1abcd00b2731640e886fb41a8a9671ad1434c599dbaa0a0de9a5aa619f29a83f'

url = "https://api.linketrack.com/track/json?user=" + user + "&token=" + token + "&codigo=" + trackingCode
payload = {}
headers= {}

response = requests.request("GET", url, headers=headers, data = payload)

if not response.ok:
    print('Nâo foi possível completar a solicitação: ',response.reason)
    print('Código de status: ',response.status_code)
    exit()


jason = response.json()

events = jason['eventos']


for i in events:
    print(i['local'])
    print(i['data'])
    print(i['hora'])
    print("Status: ", i['status'])
    if i['subStatus'] != []:
        print("Substatus: ", i['subStatus'])
    print(' ')

if jason['servico']:
    print('Serviço:',jason['servico'])

print("\033[1mConsulta em:\033[0m",time.asctime())
